Name: CI - Development

on:
  push:
    branches: [ dev ]

  pull_request:
    branches: [ main ]

jobs:

  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Run Coverage
        run: npm run test

  build:

    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
 
      - name: Build com Docker Compose
        run: docker compose build
 
      - name: Push com Docker Compose
        run: docker compose push
 

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Gerar artefato
        run: zip -r app.zip .

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app.zip

  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: app-build
          

      - name: Extrair artefato
        run: unzip app.zip

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Subir Ambiente de teste 
        run: docker compose up -d
      
      - name: Validar Comunicação (Ping)
        run: docker compose exec -T calculadora-app ping -c 1 servico-vizinho

      - name: Rodar Testes Unitátios (NPM)
        run: docker compose exec -T calculadora-app npm test